### ISSUE TITLE
如何跑自己的数据集？

### ISSUE THREAD

**Issue by Neo-cyber-hubb** [willat343/Map2DFusion#1]
您好！您的教程十分完善，我感觉您是不是复现了map2dfusion，我最近在学习这方面的工作，想用map2dfusion跑一下自己的数据集，想请教一下您图像的位姿也就是作者提供的数据集中的trajectory.txt怎么得到？

**Comment by willat343** [comment]
We are not the authors of Map2DFusion. Original repository at https://gitee.com/pi-lab/Map2DFusion.git
